name: tiny_vit
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - cuda-runtime=11.7.1=0
  - jupyter=1.0.0=py38h06a4308_8
  - matplotlib=3.7.1=py38h06a4308_1
  - torchvision=0.15.2=py38_cu117
  - pip:
      - einops==0.6.1
      - executing==1.2.0
      - fire==0.5.0
      - ipdb==0.13.13
      - kornia==0.6.12
      - rich==13.4.2
      - toolz==0.12.0
